var fs = require('fs');
var replaceAll = require('./functions.js').replaceAll;

function generate(callback) {
  var tab1 = fs.readFileSync("./views/table.html", "utf8");
  var tab2 = tab1;

  tab2 = replaceAll(tab2, "(<td.*?>).*(</td>)", "$1$2", "gm");
  tab2 = replaceAll(tab2, "tab1", "tab2");

  var warning = "<!-- THIS FILE IS AUTO GENERATED BY generate_table.js. DO NOT MAKE ANY CHANGES! --> \n";
  var output = warning + tab2 + tab1;

  fs.writeFileSync("./views/generated_table.html", output);
  console.log("Generated /views/generated_table.html");
};

exports.getTable = function() {
  var contents;

  if (fs.existsSync("./views/generated_table.html")) {
    contents = fs.readFileSync("./views/generated_table.html", "utf8");
  } else {
    generate();
    contents = fs.readFileSync("./views/generated_table.html", "utf8");
  }

  return contents;
}
